#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=sa
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring:
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
#  database:
#    driverClassName: "com.mysql.jdbc.driver"

  datasource:
      url: "jdbc:mysql://localhost:3306/baza"
      username: "root"
      password: "root"
      test-while-idle: "true"
      validationQuery: "SELECT 1"
      driver-class-name: "com.mysql.jdbc.Driver"

#ovo kaze da se koristi error stranica ako dodje do exception-a
server:
  error:
    whitelabel:
      enabled: false
  port: 8090